version: 2.1
orbs:
  node: circleci/node@2.1.1
  pulumi: pulumi/pulumi@2.0.0
jobs:
  ephem_build_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/ephemeral-env
      - pulumi/login:
          access-token: ${PULUMI_ACCESS_TOKEN}
      - run:
          name: Init Pulumi Stacks
          command: |
            cd ephemeral-env/
            ./pulumi-stack.sh $CIRCLE_BRANCH
            pulumi config set github-issue-tracker:githubToken $GITHUB_ACCESS_TOKEN --secret
            pulumi config set github-issue-tracker:domainName $CIRCLE_BRANCH.$DOMAIN_NAME
            pulumi config set aws:region us-east-1
      - pulumi/update:
          stack: $CIRCLE_BRANCH
          working_directory: ephemeral-env/
  destroy_infra:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/ephemeral-env
      - pulumi/login:
          access-token: ${PULUMI_ACCESS_TOKEN}
      - run:
          name: Set Merged Branch Name
          command: |
            export MSG="$(git log --first-parent --merges -1 --oneline 2>&1)"
            IFS="/" read void_msg BRANCH_NAME \<<< "$MSG"
            export PREVIOUS_BRANCH_NAME=$BRANCH_NAME >> $BASH_ENV
      - run:
          name: Destroy Pulumi Stacks
          command: |
            cd ephemeral-env/
            ./pulumi-stack.sh $PREVIOUS_BRANCH_NAME
            pulumi config set github-issue-tracker:githubToken $GITHUB_ACCESS_TOKEN --secret
            pulumi config set github-issue-tracker:domainName $PREVIOUS_BRANCH_NAME.$DOMAIN_NAME
            pulumi config set aws:region us-east-1
      - pulumi/refresh:
          stack: $PREVIOUS_BRANCH_NAME
          working_directory: ephemeral-env/
      - pulumi/destroy:
          stack: $PREVIOUS_BRANCH_NAME
          working_directory: ephemeral-env/
      - pulumi/stack_rm:
          stack: $PREVIOUS_BRANCH_NAME
          working_directory: ephemeral-env/
workflows:
    build_test:
      jobs:
        - ephem_build_test:
            filters:
              branches:
                ignore: master
        - destroy_infra:
             - ephem_build_test
            filters:
              branches:
                only: master