version: 2.1
orbs:
  node: circleci/node@2.1.1
  pulumi: pulumi/pulumi@2.0.0
jobs:
  ephem_build_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/ephemeral-env
      - pulumi/login:
          access-token: ${PULUMI_ACCESS_TOKEN}
      # - pulumi/update:
      #     stack: k8s
      #     working_directory: ${HOME}/project/pulumi/gcp/gke/
workflows:
    build_test:
      jobs:
        - ephem_build_test